// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: explorer/v1/chain.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBlockNumerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	BlockNumber   uint64                 `protobuf:"varint,2,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockNumerReply) Reset() {
	*x = GetBlockNumerReply{}
	mi := &file_explorer_v1_chain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockNumerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockNumerReply) ProtoMessage() {}

func (x *GetBlockNumerReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockNumerReply.ProtoReflect.Descriptor instead.
func (*GetBlockNumerReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{0}
}

func (x *GetBlockNumerReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetBlockNumerReply) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type GetNetworkIdReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NetworkId     uint64                 `protobuf:"varint,2,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkIdReply) Reset() {
	*x = GetNetworkIdReply{}
	mi := &file_explorer_v1_chain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkIdReply) ProtoMessage() {}

func (x *GetNetworkIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkIdReply.ProtoReflect.Descriptor instead.
func (*GetNetworkIdReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{1}
}

func (x *GetNetworkIdReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetNetworkIdReply) GetNetworkId() uint64 {
	if x != nil {
		return x.NetworkId
	}
	return 0
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_explorer_v1_chain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetBalanceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Balance       uint64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceReply) Reset() {
	*x = GetBalanceReply{}
	mi := &file_explorer_v1_chain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceReply) ProtoMessage() {}

func (x *GetBalanceReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceReply.ProtoReflect.Descriptor instead.
func (*GetBalanceReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetBalanceReply) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type GetTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_explorer_v1_chain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{4}
}

func (x *GetTransactionRequest) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

type GetTransactionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Transaction   string                 `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionReply) Reset() {
	*x = GetTransactionReply{}
	mi := &file_explorer_v1_chain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReply) ProtoMessage() {}

func (x *GetTransactionReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReply.ProtoReflect.Descriptor instead.
func (*GetTransactionReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransactionReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetTransactionReply) GetTransaction() string {
	if x != nil {
		return x.Transaction
	}
	return ""
}

type GetTransactionReceiptRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionHash string                 `protobuf:"bytes,1,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionReceiptRequest) Reset() {
	*x = GetTransactionReceiptRequest{}
	mi := &file_explorer_v1_chain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptRequest) ProtoMessage() {}

func (x *GetTransactionReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionReceiptRequest) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

type GetTransactionReceiptReply struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	TransactionReceipt string                 `protobuf:"bytes,2,opt,name=transaction_receipt,json=transactionReceipt,proto3" json:"transaction_receipt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTransactionReceiptReply) Reset() {
	*x = GetTransactionReceiptReply{}
	mi := &file_explorer_v1_chain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionReceiptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionReceiptReply) ProtoMessage() {}

func (x *GetTransactionReceiptReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionReceiptReply.ProtoReflect.Descriptor instead.
func (*GetTransactionReceiptReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionReceiptReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetTransactionReceiptReply) GetTransactionReceipt() string {
	if x != nil {
		return x.TransactionReceipt
	}
	return ""
}

type GetBlockByNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByNumberRequest) Reset() {
	*x = GetBlockByNumberRequest{}
	mi := &file_explorer_v1_chain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByNumberRequest) ProtoMessage() {}

func (x *GetBlockByNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByNumberRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByNumberRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlockByNumberRequest) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

type GetBlockByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockByHashRequest) Reset() {
	*x = GetBlockByHashRequest{}
	mi := &file_explorer_v1_chain_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockByHashRequest) ProtoMessage() {}

func (x *GetBlockByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockByHashRequest.ProtoReflect.Descriptor instead.
func (*GetBlockByHashRequest) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlockByHashRequest) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

type GetBlockReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *Status                `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Block         string                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockReply) Reset() {
	*x = GetBlockReply{}
	mi := &file_explorer_v1_chain_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockReply) ProtoMessage() {}

func (x *GetBlockReply) ProtoReflect() protoreflect.Message {
	mi := &file_explorer_v1_chain_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockReply.ProtoReflect.Descriptor instead.
func (*GetBlockReply) Descriptor() ([]byte, []int) {
	return file_explorer_v1_chain_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockReply) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetBlockReply) GetBlock() string {
	if x != nil {
		return x.Block
	}
	return ""
}

var File_explorer_v1_chain_proto protoreflect.FileDescriptor

const file_explorer_v1_chain_proto_rawDesc = "" +
	"\n" +
	"\x17explorer/v1/chain.proto\x12\x0fapi.explorer.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x18explorer/v1/common.proto\"h\n" +
	"\x12GetBlockNumerReply\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.api.explorer.v1.StatusR\x06status\x12!\n" +
	"\fblock_number\x18\x02 \x01(\x04R\vblockNumber\"c\n" +
	"\x11GetNetworkIdReply\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.api.explorer.v1.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"network_id\x18\x02 \x01(\x04R\tnetworkId\"-\n" +
	"\x11GetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\\\n" +
	"\x0fGetBalanceReply\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.api.explorer.v1.StatusR\x06status\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x04R\abalance\"B\n" +
	"\x15GetTransactionRequest\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\"h\n" +
	"\x13GetTransactionReply\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.api.explorer.v1.StatusR\x06status\x12 \n" +
	"\vtransaction\x18\x02 \x01(\tR\vtransaction\"I\n" +
	"\x1cGetTransactionReceiptRequest\x12)\n" +
	"\x10transaction_hash\x18\x01 \x01(\tR\x0ftransactionHash\"~\n" +
	"\x1aGetTransactionReceiptReply\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.api.explorer.v1.StatusR\x06status\x12/\n" +
	"\x13transaction_receipt\x18\x02 \x01(\tR\x12transactionReceipt\"<\n" +
	"\x17GetBlockByNumberRequest\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\"6\n" +
	"\x15GetBlockByHashRequest\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\"V\n" +
	"\rGetBlockReply\x12/\n" +
	"\x06status\x18\x01 \x01(\v2\x17.api.explorer.v1.StatusR\x06status\x12\x14\n" +
	"\x05block\x18\x02 \x01(\tR\x05block2\xd1\a\n" +
	"\x05Chain\x12p\n" +
	"\rGetBlockNumer\x12\x16.google.protobuf.Empty\x1a#.api.explorer.v1.GetBlockNumerReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/chain/v1/get_block_number\x12l\n" +
	"\fGetNetworkId\x12\x16.google.protobuf.Empty\x1a\".api.explorer.v1.GetNetworkIdReply\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/chain/v1/get_network_id\x12{\n" +
	"\n" +
	"GetBalance\x12\".api.explorer.v1.GetBalanceRequest\x1a .api.explorer.v1.GetBalanceReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/chain/v1/get_balance/{address}\x12\x94\x01\n" +
	"\x0eGetTransaction\x12&.api.explorer.v1.GetTransactionRequest\x1a$.api.explorer.v1.GetTransactionReply\"4\x82\xd3\xe4\x93\x02.\x12,/chain/v1/get_transaction/{transaction_hash}\x12\xb1\x01\n" +
	"\x15GetTransactionReceipt\x12-.api.explorer.v1.GetTransactionReceiptRequest\x1a+.api.explorer.v1.GetTransactionReceiptReply\"<\x82\xd3\xe4\x93\x026\x124/chain/v1/get_transaction_receipt/{transaction_hash}\x12\x92\x01\n" +
	"\x10GetBlockByNumber\x12(.api.explorer.v1.GetBlockByNumberRequest\x1a\x1e.api.explorer.v1.GetBlockReply\"4\x82\xd3\xe4\x93\x02.\x12,/chain/v1/get_block_by_number/{block_number}\x12\x8a\x01\n" +
	"\x0eGetBlockByHash\x12&.api.explorer.v1.GetBlockByHashRequest\x1a\x1e.api.explorer.v1.GetBlockReply\"0\x82\xd3\xe4\x93\x02*\x12(/chain/v1/get_block_by_hash/{block_hash}B0\n" +
	"\x0fapi.explorer.v1P\x01Z\x1bexplorer/api/explorer/v1;v1b\x06proto3"

var (
	file_explorer_v1_chain_proto_rawDescOnce sync.Once
	file_explorer_v1_chain_proto_rawDescData []byte
)

func file_explorer_v1_chain_proto_rawDescGZIP() []byte {
	file_explorer_v1_chain_proto_rawDescOnce.Do(func() {
		file_explorer_v1_chain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_explorer_v1_chain_proto_rawDesc), len(file_explorer_v1_chain_proto_rawDesc)))
	})
	return file_explorer_v1_chain_proto_rawDescData
}

var file_explorer_v1_chain_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_explorer_v1_chain_proto_goTypes = []any{
	(*GetBlockNumerReply)(nil),           // 0: api.explorer.v1.GetBlockNumerReply
	(*GetNetworkIdReply)(nil),            // 1: api.explorer.v1.GetNetworkIdReply
	(*GetBalanceRequest)(nil),            // 2: api.explorer.v1.GetBalanceRequest
	(*GetBalanceReply)(nil),              // 3: api.explorer.v1.GetBalanceReply
	(*GetTransactionRequest)(nil),        // 4: api.explorer.v1.GetTransactionRequest
	(*GetTransactionReply)(nil),          // 5: api.explorer.v1.GetTransactionReply
	(*GetTransactionReceiptRequest)(nil), // 6: api.explorer.v1.GetTransactionReceiptRequest
	(*GetTransactionReceiptReply)(nil),   // 7: api.explorer.v1.GetTransactionReceiptReply
	(*GetBlockByNumberRequest)(nil),      // 8: api.explorer.v1.GetBlockByNumberRequest
	(*GetBlockByHashRequest)(nil),        // 9: api.explorer.v1.GetBlockByHashRequest
	(*GetBlockReply)(nil),                // 10: api.explorer.v1.GetBlockReply
	(*Status)(nil),                       // 11: api.explorer.v1.Status
	(*emptypb.Empty)(nil),                // 12: google.protobuf.Empty
}
var file_explorer_v1_chain_proto_depIdxs = []int32{
	11, // 0: api.explorer.v1.GetBlockNumerReply.status:type_name -> api.explorer.v1.Status
	11, // 1: api.explorer.v1.GetNetworkIdReply.status:type_name -> api.explorer.v1.Status
	11, // 2: api.explorer.v1.GetBalanceReply.status:type_name -> api.explorer.v1.Status
	11, // 3: api.explorer.v1.GetTransactionReply.status:type_name -> api.explorer.v1.Status
	11, // 4: api.explorer.v1.GetTransactionReceiptReply.status:type_name -> api.explorer.v1.Status
	11, // 5: api.explorer.v1.GetBlockReply.status:type_name -> api.explorer.v1.Status
	12, // 6: api.explorer.v1.Chain.GetBlockNumer:input_type -> google.protobuf.Empty
	12, // 7: api.explorer.v1.Chain.GetNetworkId:input_type -> google.protobuf.Empty
	2,  // 8: api.explorer.v1.Chain.GetBalance:input_type -> api.explorer.v1.GetBalanceRequest
	4,  // 9: api.explorer.v1.Chain.GetTransaction:input_type -> api.explorer.v1.GetTransactionRequest
	6,  // 10: api.explorer.v1.Chain.GetTransactionReceipt:input_type -> api.explorer.v1.GetTransactionReceiptRequest
	8,  // 11: api.explorer.v1.Chain.GetBlockByNumber:input_type -> api.explorer.v1.GetBlockByNumberRequest
	9,  // 12: api.explorer.v1.Chain.GetBlockByHash:input_type -> api.explorer.v1.GetBlockByHashRequest
	0,  // 13: api.explorer.v1.Chain.GetBlockNumer:output_type -> api.explorer.v1.GetBlockNumerReply
	1,  // 14: api.explorer.v1.Chain.GetNetworkId:output_type -> api.explorer.v1.GetNetworkIdReply
	3,  // 15: api.explorer.v1.Chain.GetBalance:output_type -> api.explorer.v1.GetBalanceReply
	5,  // 16: api.explorer.v1.Chain.GetTransaction:output_type -> api.explorer.v1.GetTransactionReply
	7,  // 17: api.explorer.v1.Chain.GetTransactionReceipt:output_type -> api.explorer.v1.GetTransactionReceiptReply
	10, // 18: api.explorer.v1.Chain.GetBlockByNumber:output_type -> api.explorer.v1.GetBlockReply
	10, // 19: api.explorer.v1.Chain.GetBlockByHash:output_type -> api.explorer.v1.GetBlockReply
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_explorer_v1_chain_proto_init() }
func file_explorer_v1_chain_proto_init() {
	if File_explorer_v1_chain_proto != nil {
		return
	}
	file_explorer_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_explorer_v1_chain_proto_rawDesc), len(file_explorer_v1_chain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_explorer_v1_chain_proto_goTypes,
		DependencyIndexes: file_explorer_v1_chain_proto_depIdxs,
		MessageInfos:      file_explorer_v1_chain_proto_msgTypes,
	}.Build()
	File_explorer_v1_chain_proto = out.File
	file_explorer_v1_chain_proto_goTypes = nil
	file_explorer_v1_chain_proto_depIdxs = nil
}
